import { Injectable } from '@angular/core';
import {
  FinancialScorecardModel,
  OperationalScorecardModel,
  PrioritiesScorecardModel,
  RelationalScorecardModel,
  StrategicScorecardModel,
} from '../models/scorecard.model';
import { BehaviorSubject } from 'rxjs';
@Injectable({ providedIn: 'root' })
export class ScorecardService {
  private currMode:BehaviorSubject<'editMode' | 'viewMode'> = new BehaviorSubject<'editMode' | 'viewMode'>('viewMode')
  financialScorcardData!: FinancialScorecardModel[];
  strategicScorcardData!: StrategicScorecardModel[];
  rationalScorcardData!: RelationalScorecardModel[];
  operationalScorcardData!: OperationalScorecardModel[];
  prioritieslScorcardData!: PrioritiesScorecardModel[];
  constructor() {
    this.financialScorcardData = [
      {
        id:1,
        title: 'transforming costs to maximize value',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            weight: 5,
            unit: 'SR Bn',
            baseline: null,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            // achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
      {
        id:2,
        title: 'transforming costs to maximize value11',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            weight: 5,
            unit: 'SR Bn',
            baseline: null,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
      {
        id:3,
        title: 'transforming costs to maximize value1133',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            weight: 5,
            unit: 'SR Bn',
            baseline: null,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
    ];
    this.strategicScorcardData = [
      {
        id:1,
        title: 'execute strategy right',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 5,
            unit: 'SR Bn',
            baseline: 12738,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
    ];
    this.rationalScorcardData = [
      {
        id:1,
        title: 'delivered unparalleled CEX',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            actual: 99.99,
            weight: 5,
            unit: 'SR Bn',
            baseline: 12738,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
    ];
    this.operationalScorcardData = [
      {
        id:1,
        title: 'unlock analytics capabilities',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 5,
            unit: 'SR Bn',
            baseline: 12738,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            formula: 'linear',
            actual: 50,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
      {
        id:2,
        title: 'execute technology right',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 5,
            unit: 'SR Bn',
            baseline: 12738,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
    ];
    this.prioritieslScorcardData = [
      {
        id:1,
        title: 'corporate priorities',
        kpisData: [
          {
            id: 1,
            title: 'stc KSA EBIT',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 5,
            unit: 'SR Bn',
            baseline: 12738,
            target: 12537,
            ceiling: 110,
            threshold: 85,
          },
          {
            id: 2,
            title: 'CAD business efficiency OPEX savings',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 3,
            title: 'CAD business 123',
            achievedStatus: 1,
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
          {
            id: 4,
            title: 'CAD business test',
            achievedStatus: 1,
            formula: 'linear',
            actual: 99.99,
            weight: 20,
            unit: '%',
            baseline: 145.68,
            target: 100,
            ceiling: 90,
            threshold: 55,
          },
        ],
      },
    ];
  }
  setEditMode(mode:'editMode' | 'viewMode')
  {
    this.currMode.next(mode);
  }
  getCurrentMode():BehaviorSubject<'editMode' | 'viewMode'>
  {
    return this.currMode
  }
}
